In [1]:
# from collections import defaultdict

## see examples in https://www.gurobi.com/resource/modeling-examples-using-the-gurobi-python-api-in-jupyter-notebook/
# import gurobipy as gp
# from gurobipy import GRB

# import math
# import numpy as np
# from datetime import datetime
import sys

%matplotlib notebook    
import matplotlib.pyplot as plt

# from fruit_distribution import *   # import module to create the various desired fruit distributions 
from IG_data_analysis import *     # import module to analyze the data from the snapshots
from MIP_melon import *

# tested with Python 3.7.0 & Gurobi 9.0

## based on the Gurobi technician routing scheduling example
# https://gurobi.github.io/modeling-examples/technician_routing_scheduling/technician_routing_scheduling.html

In [2]:
# def printScen(scenStr):
#     sLen = len(scenStr)
#     print("\n" + "*"*sLen + "\n" + scenStr + "\n" + "*"*sLen + "\n")

In [8]:
##################### RUN MULTIPLE MIP PYTHON SCRIPT #####################
## command line arguments
    # args[0] == n_arm
    # args[1] == n_row
    # args[2] == density
    # args[3] == v_vy in cmps
%run -i MIP_full_multiple.py 3 3 16 3


length of the full dataset: 12.0 m
vehicle view distance: 2.0999999999999996 m
number of snapshots: 6

this seed [[1.3804855349347703e+38, 3.268803194267739e+38, 2.9189795199471455e+38, 2.073550919973278e+38, 3.6861458259937537e+36, 1.8451681294991773e+38]]


The density of fruits in the file is: 65.39470541590447 f/m^2 

x-lim [0.2 1.2] y-lim [ 0. 12.] z-lim [0. 2.]
Total fruit in the orchard row 1156

------------------------------------
number of fruits in this snaphsot: 297
------------------------------------

number of fruit in each row, rounded down 99
bottom z-axis edges [[0.         0.97171914 1.47245781]
 [0.         0.97171914 1.47245781]
 [0.         0.97171914 1.47245781]]

top z-axis edges [[0.97151914 1.47225781 2.        ]
 [0.97151914 1.47225781 2.        ]
 [0.97151914 1.47225781 2.        ]]

the indexes of the fruits in the horizon are: []

the density of fruits in each cell in this snapshot is:
 73.64328643636847

the density of fruits in each cell in this snapsho

bottom z-axis edges [[0.         0.96568114 1.48960328]
 [0.         0.96568114 1.48960328]
 [0.         0.96568114 1.48960328]]

top z-axis edges [[0.96548114 1.48940328 2.        ]
 [0.96548114 1.48940328 2.        ]
 [0.96548114 1.48940328 2.        ]]

the indexes of the fruits in the horizon are: []

the density of fruits in each cell in this snapshot is:
 79.88232893127463

the density of fruits in each cell in this snapshot is:
 [[ 47.34870923  59.18588653  48.82835639]
 [114.56456543  35.46046073 133.65865967]
 [123.15350185  69.9735806   86.76723994]]

the density of fruits in each row in this snapshot is:
 [51.78765072 94.56122861 93.29810747]

the R value of this snapshot is: 0


***************************
Solving base scenario model
***************************


----------------------------------------------------------------
 Vehicle location at start of this snapshot 2.1 m on y-axis 
----------------------------------------------------------------

number of fruits: [0, 

Set parameter TimeLimit to value 60
Gurobi Optimizer version 9.5.0 build v9.5.0rc5 (linux64)
Thread count: 2 physical cores, 4 logical processors, using up to 4 threads
Optimize a model with 427641 rows, 5508 columns and 1690044 nonzeros
Model fingerprint: 0xcb71d669
Variable types: 2754 continuous, 2754 integer (2754 binary)
Coefficient statistics:
  Matrix range     [1e+00, 8e+01]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 5e+02]
  RHS range        [1e+00, 3e+02]
Found heuristic solution: objective 182.0000000
Presolve removed 420619 rows and 4908 columns
Presolve time: 1.76s
Presolved: 7022 rows, 600 columns, 27960 nonzeros
Found heuristic solution: objective 276.0000000
Variable types: 291 continuous, 309 integer (309 binary)
Starting NoRel heuristic
Found heuristic solution: objective 277.0000000
Found heuristic solution: objective 281.0000000
Found heuristic solution: objective 291.0000000
Found heuristic solution: objective 294.0000000
Found heuristic solution:

Set parameter TimeLimit to value 60
Gurobi Optimizer version 9.5.0 build v9.5.0rc5 (linux64)
Thread count: 2 physical cores, 4 logical processors, using up to 4 threads
Optimize a model with 14235 rows, 972 columns and 53304 nonzeros
Model fingerprint: 0x04ba79ab
Variable types: 486 continuous, 486 integer (486 binary)
Coefficient statistics:
  Matrix range     [1e+00, 8e+01]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 5e+02]
  RHS range        [1e+00, 4e+02]
Found heuristic solution: objective 44.0000000
Presolve removed 14235 rows and 972 columns
Presolve time: 0.03s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.04 seconds (0.01 work units)
Thread count was 1 (of 4 available processors)

Solution count 2: 52 44 

Optimal solution found (tolerance 1.00e-04)
Best objective 5.200000000000e+01, best bound 5.200000000000e+01, gap 0.0000%

set M value: 80


fruit picked by after rows are added together [[[1111, 1112, 1116, 1128, 1143,

In [3]:
##################### RUN MIP PYTHON SCRIPT #####################
# %run -i MIP_solve_full.py


The original density of the file is: 6.075366933041988 f/m^2 
  The desired density is: 16 f/m^2 

x-lim [0.2 1.2] y-lim [0. 6.] z-lim [0. 2.]
Total fruit in the orchard row 877


TypeError: set_zEdges() missing 2 required positional arguments: 'numFruit' and 'sortedFruit'

In [2]:
##################### RUN MIP PER ROW PYTHON SCRIPT #####################
## command line arguments
    # args[0] == n_arm
    # args[1] == n_row
    # args[2] == density
    # args[3] == v_vy in cmps
%run -i MIP_solve_per_row.py 3 3 16 3


length of the full dataset: 16.5 m
vehicle view distance: 2.0999999999999996 m
number of snapshots: 8


The density of fruits in the file is: 53.972205934411086 f/m^2 

x-lim [0.2 1.2] y-lim [ 0.  16.5] z-lim [0. 2.]
Total fruit in the orchard row 1183

------------------------------------
number of fruits in this snaphsot: 109
------------------------------------

number of fruit in each row, rounded down 36
bottom z-axis edges [[0.         0.65086046 0.85764225]
 [0.         0.65086046 0.85764225]
 [0.         0.65086046 0.85764225]]

top z-axis edges [[0.65086046 0.85764225 2.        ]
 [0.65086046 0.85764225 2.        ]
 [0.65086046 0.85764225 2.        ]]

the indexes of the fruits in the horizon are: []

the density of fruits in each cell in this snapshot is:
 41.6600258722834

the density of fruits in each cell in this snapshot is:
 [[ 57.06731195  21.94896614   2.19489661]
 [110.53750484 131.263287     6.90859405]
 [ 20.00874323  21.25928968   3.75163936]]

the density of frui

Set parameter TimeLimit to value 60
Gurobi Optimizer version 9.5.0 build v9.5.0rc5 (linux64)
Thread count: 2 physical cores, 4 logical processors, using up to 4 threads
Optimize a model with 56733 rows, 1152 columns and 222141 nonzeros
Model fingerprint: 0x64ba6c9d
Variable types: 576 continuous, 576 integer (576 binary)
Coefficient statistics:
  Matrix range     [1e+00, 8e+01]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 6e+02]
  RHS range        [1e+00, 2e+02]
Found heuristic solution: objective 44.0000000
Presolve removed 54539 rows and 774 columns
Presolve time: 0.22s
Presolved: 2194 rows, 378 columns, 8688 nonzeros
Variable types: 180 continuous, 198 integer (198 binary)
Found heuristic solution: objective 54.0000000
Starting NoRel heuristic
Found heuristic solution: objective 58.0000000
Found heuristic solution: objective 62.0000000
Found heuristic solution: objective 63.0000000
Found heuristic solution: objective 64.0000000
Found heuristic solution: objective 65.

Set parameter TimeLimit to value 60
Gurobi Optimizer version 9.5.0 build v9.5.0rc5 (linux64)
Thread count: 2 physical cores, 4 logical processors, using up to 4 threads
Optimize a model with 6423 rows, 378 columns and 24126 nonzeros
Model fingerprint: 0x4732a45c
Variable types: 189 continuous, 189 integer (189 binary)
Coefficient statistics:
  Matrix range     [1e+00, 8e+01]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 6e+02]
  RHS range        [1e+00, 3e+02]
Found heuristic solution: objective 18.0000000
Presolve removed 6423 rows and 378 columns
Presolve time: 0.01s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.02 seconds (0.01 work units)
Thread count was 1 (of 4 available processors)

Solution count 2: 22 18 

Optimal solution found (tolerance 1.00e-04)
Best objective 2.200000000000e+01, best bound 2.200000000000e+01, gap 0.0000%

set M value: 80

[[[17, 24, 28, 33, 38, 42, 44, 45, 47, 48, 52, 55, 58, 62, 91], [20, 26, 30, 41, 

Set parameter TimeLimit to value 60
Gurobi Optimizer version 9.5.0 build v9.5.0rc5 (linux64)
Thread count: 2 physical cores, 4 logical processors, using up to 4 threads
Optimize a model with 33068 rows, 876 columns and 128625 nonzeros
Model fingerprint: 0xb3011ecc
Variable types: 438 continuous, 438 integer (438 binary)
Coefficient statistics:
  Matrix range     [1e+00, 8e+01]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 6e+02]
  RHS range        [1e+00, 3e+02]
Found heuristic solution: objective 41.0000000
Presolve removed 32083 rows and 606 columns
Presolve time: 0.09s
Presolved: 985 rows, 270 columns, 3984 nonzeros
Variable types: 102 continuous, 168 integer (168 binary)
Found heuristic solution: objective 48.0000000
Starting NoRel heuristic
Found heuristic solution: objective 49.0000000
NoRel heuristic complete

Explored 0 nodes (0 simplex iterations) in 0.13 seconds (0.08 work units)
Thread count was 4 (of 4 available processors)

Solution count 3: 49 48 41 

Optim

Set parameter TimeLimit to value 60
Gurobi Optimizer version 9.5.0 build v9.5.0rc5 (linux64)
Thread count: 2 physical cores, 4 logical processors, using up to 4 threads
Optimize a model with 35795 rows, 912 columns and 139383 nonzeros
Model fingerprint: 0xe09f97ef
Variable types: 456 continuous, 456 integer (456 binary)
Coefficient statistics:
  Matrix range     [1e+00, 8e+01]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 6e+02]
  RHS range        [1e+00, 4e+02]
Found heuristic solution: objective 42.0000000
Presolve removed 34495 rows and 660 columns
Presolve time: 0.09s
Presolved: 1300 rows, 252 columns, 5136 nonzeros
Variable types: 117 continuous, 135 integer (135 binary)
Found heuristic solution: objective 46.0000000
Starting NoRel heuristic
Found heuristic solution: objective 49.0000000
Found heuristic solution: objective 50.0000000
Found heuristic solution: objective 51.0000000
NoRel heuristic complete

Explored 0 nodes (0 simplex iterations) in 0.14 seconds (0.08

Set parameter NoRelHeurTime to value 15
Set parameter TimeLimit to value 60
Gurobi Optimizer version 9.5.0 build v9.5.0rc5 (linux64)
Thread count: 2 physical cores, 4 logical processors, using up to 4 threads
Optimize a model with 27938 rows, 804 columns and 108405 nonzeros
Model fingerprint: 0x0d8f5082
Variable types: 402 continuous, 402 integer (402 binary)
Coefficient statistics:
  Matrix range     [1e+00, 8e+01]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 6e+02]
  RHS range        [1e+00, 5e+02]
Found heuristic solution: objective 36.0000000
Presolve removed 26872 rows and 570 columns
Presolve time: 0.07s
Presolved: 1066 rows, 234 columns, 4209 nonzeros
Variable types: 108 continuous, 126 integer (126 binary)
Found heuristic solution: objective 41.0000000
Starting NoRel heuristic
Found heuristic solution: objective 44.0000000
Found heuristic solution: objective 45.0000000
NoRel heuristic complete

Explored 0 nodes (0 simplex iterations) in 0.12 seconds (0.06 work u

Set parameter TimeLimit to value 60
Gurobi Optimizer version 9.5.0 build v9.5.0rc5 (linux64)
Thread count: 2 physical cores, 4 logical processors, using up to 4 threads
Optimize a model with 59092 rows, 1176 columns and 231474 nonzeros
Model fingerprint: 0x69a9924a
Variable types: 588 continuous, 588 integer (588 binary)
Coefficient statistics:
  Matrix range     [1e+00, 8e+01]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 6e+02]
  RHS range        [1e+00, 6e+02]
Found heuristic solution: objective 51.0000000
Presolve removed 56620 rows and 786 columns
Presolve time: 0.16s
Presolved: 2472 rows, 390 columns, 9801 nonzeros
Variable types: 186 continuous, 204 integer (204 binary)
Found heuristic solution: objective 59.0000000
Starting NoRel heuristic
Found heuristic solution: objective 60.0000000
Found heuristic solution: objective 61.0000000
Found heuristic solution: objective 63.0000000
Found heuristic solution: objective 64.0000000
Found heuristic solution: objective 66.

Set parameter TimeLimit to value 60
Gurobi Optimizer version 9.5.0 build v9.5.0rc5 (linux64)
Thread count: 2 physical cores, 4 logical processors, using up to 4 threads
Optimize a model with 55573 rows, 1140 columns and 217548 nonzeros
Model fingerprint: 0xa89575df
Variable types: 570 continuous, 570 integer (570 binary)
Coefficient statistics:
  Matrix range     [1e+00, 8e+01]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 6e+02]
  RHS range        [1e+00, 6e+02]
Found heuristic solution: objective 43.0000000
Presolve removed 52251 rows and 762 columns
Presolve time: 0.19s
Presolved: 3322 rows, 378 columns, 13212 nonzeros
Variable types: 180 continuous, 198 integer (198 binary)
Found heuristic solution: objective 48.0000000
Starting NoRel heuristic
Found heuristic solution: objective 55.0000000
Found heuristic solution: objective 61.0000000
Found heuristic solution: objective 62.0000000
Found heuristic solution: objective 63.0000000
Found heuristic solution: objective 64

AttributeError: 'MIP_melon' object has no attribute 'sortedFruit'